config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'
  get 'say/goodye'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
  end

  def goodye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/say/goodye.html.erb
<h1>Goodbye!</h1>
<p>
    It was nice having you here!

<p> 
    It was nice having you here. </p>

<p> 
    Say <%= link_to "Hello" , say_hello_path %> again. </p>

app/views/say/hello.html.erb
<h1>Hello from Rails!</h1>
<img width="600" src="https://images.pexels.com/photos/132037/pexels-photo-132037.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500">
<p> It is now <%= @time %> </p>

<p>
    Time to say <%= link_to "goodbye" , say_goodye_path %>!
</p>